default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: scriptures_development
  queue:
    <<: *default
    database: scriptures_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: scriptures_test

production:
  primary:
    <<: *default
    database: scriptures_production
    username: scriptures
    password: <%= ENV["SCRIPTURES_DATABASE_PASSWORD"] %>
  cache:
    <<: *default
    database: scriptures_production_cache
    username: scriptures
    password: <%= ENV["SCRIPTURES_DATABASE_PASSWORD"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: scriptures_production_queue
    username: scriptures
    password: <%= ENV["SCRIPTURES_DATABASE_PASSWORD"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: scriptures_production_cable
    username: scriptures
    password: <%= ENV["SCRIPTURES_DATABASE_PASSWORD"] %>
    migrations_paths: db/cable_migrate
